SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `java2` DEFAULT CHARACTER SET utf8 ;
USE `java2` ;

DROP TABLE IF EXISTS `Users` ;
DROP TABLE IF EXISTS `Accounts` ;
DROP TABLE IF EXISTS `Transactions` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`)
)
CREATE TABLE IF NOT EXISTS `Accounts` (
  `account_number` VARCHAR(10) NOT NULL,
  `currency` VARCHAR(3) NOT NULL,
  `balance` DEC NOT NULL ,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`account_number`),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);
CREATE TABLE IF NOT EXISTS `Transactions` (
  `transaction_id` BIGINT NOT NULL AUTO_INCREMENT,
  `from_account_number` VARCHAR(10) NOT NULL,
  `to_account_number` VARCHAR(10) NOT NULL ,
  `dateTime` DATETIME NOT NULL,
  `amount` DEC NOT NULL,
  PRIMARY KEY (`transaction_id`),
  FOREIGN KEY (from_account_number) REFERENCES Accounts(account_number),
  FOREIGN KEY (to_account_number) REFERENCES Accounts(account_number)
);

ENGINE = InnoDB
AUTO_INCREMENT = 1002;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
